version: '3'

services:
  execution:
    container_name: execution
    build: ./go-ethereum
    expose:
      - "8551"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303"
      - "30303:30303/udp"
    command: ["--mainnet", "--http.vhosts=*", "--http", "--ws", "--http.api=eth,net,engine,admin", "--http.addr=0.0.0.0", "--authrpc.addr=0.0.0.0", "--authrpc.jwtsecret=/jwt/jwt.hex"]
    volumes:
        - .execution-data:/data
        - .jwt:/jwt

  node:
    container_name: node
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    depends_on:
      - execution
    ports:
      - "3500:3500"
      - "13000:13000"
      - "12000:12000/udp"
    volumes:
        - .consensus-data:/data
        - .jwt:/jwt
    command: ["--mainnet", "--datadir=/data", "--jwt-secret=/jwt/jwt.hex", "--checkpoint-sync-url=https://beaconstate.info", "--genesis-beacon-api-url=https://beaconstate.info", "--rpc-host=0.0.0.0", "--grpc-gateway-host=0.0.0.0", "--monitoring-host=0.0.0.0", "--execution-endpoint=http://execution:8551", "--accept-terms-of-use"]
