version: '3'

services:
  execution:
    container_name: execution
    build: ./go-ethereum
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
    expose:
      - "8551"
    # ports:
    #  - "8545:8545"
    #  - "8546:8546"
    #  - "8551:8551"
    #  - "30303:30303"
    #  - "30303:30303/udp"
    command: ["--syncmode=full", "--history.state=1000", "--history.transactions=1000", "--mainnet", "--http.vhosts=*", "--http", "--ws", "--http.api=eth,net,engine,admin", "--http.addr=0.0.0.0", "--authrpc.addr=0.0.0.0", "--authrpc.jwtsecret=/jwt/jwt.hex"]
    volumes:
        - .execution-data:/root
        - .jwt:/jwt

  beacon:
    container_name: beacon
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
    #depends_on:
    #  - execution
    ports:
      - "3500:3500"
      - "13000:13000"
      - "12000:12000/udp"
    volumes:
        - .consensus-data:/data
        - .jwt:/jwt
    command: ["--mainnet", "--datadir=/data", "--jwt-secret=/jwt/jwt.hex", "--checkpoint-sync-url=https://beaconstate.info", "--genesis-beacon-api-url=https://beaconstate.info", "--rpc-host=0.0.0.0", "--grpc-gateway-host=0.0.0.0", "--monitoring-host=0.0.0.0", "--execution-endpoint=http://192.168.1.20:8551", "--accept-terms-of-use"]
